config/routes.rb
Rails.application.routes.draw do
  # home page
  root "home_page#index"

  # sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # carts
  get '/cart', to: 'carts#show'

  # cart items
  post '/cart_items', to: 'cart_items#create'

  # users
  get '/signup', to: 'users#new'

  # orders
  get '/orders', to: 'orders#index'
  post 'orders/new', to: 'orders#create'

  # order items
  post '/order_items', to: 'order_items#create'

  # resources
  resources :users, only: %i[show new create edit update]
  resources :home_page
  resources :dishes
  resources :cart_items
  resources :orders, only: %i[show new create]
  resources :order_items

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :orders, only: %i[edit index update]
    get '/', to: 'base#index'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :check_logged_in_as_admin

  layout 'admin'

  def index
      @orders = Order.all
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.finalized = true
    @order.save
    redirect_to admin_orders_path
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def show
    if logged_in?
      @order = current_user.orders.find(params[:id])
    else
      @order = Order.find_by(id: params[:id])
    end
    @order_items = @order.order_items
  end

  def destroy
    Order.destroy(current_user.orders.find(prams[:id]))
    redirect_to '/orders'
  end

  def create
    @order = Order.new
    @order.user_id = current_user.id
    @order.total_price = params[:total_price]
    @order.finalized = false
    @cart_items = current_user.cart.cart_items
    # Take all the items that are currently in the cart and make a copy of each in an OrderItem
    if @order.save
      copy_cart_items(@cart_items, @order.id)
      flash[:success] = 'Your order has been placed!'
      redirect_to '/cart_items'
      @cart_items.destroy_all
    else
      flash[:danger] = 'Could not process order!'
      redirect_to '/cart_items'
    end
  end
end

app/helpers/orders_helper.rb
require 'barby'
require 'barby/barcode'
require 'barby/barcode/qr_code'
require 'barby/outputter/png_outputter'

module OrdersHelper
  def copy_cart_items(cart_items, order_id)
    cart_items.each do |ci|
      OrderItem.create(order_id: order_id, dish_id: ci.dish_id, quantity: ci.quantity)
    end
  end

  def generate_qr(text)
    barcode = Barby::QrCode.new(text, level: :q, size: 5)
    base64_output = Base64.encode64(barcode.to_png({xdim: 5}))
    "data:image/png;base64,#{base64_output}"
  end
end

app/views/admin/orders/index.html.erb
<h1 class="centered-title">All orders:</h1>
<div class="container admin-orders-container">
  <div class="col col-md-6">
    <% @orders.each do |o| %>
      <div class="orders-container">
        <ul class="list-group">
          <li class="list-group-item list-group-item-action list-group-item-primary">User name: <%= o.user.name %></li>
          <li class="list-group-item list-group-item-action list-group-item-primary">Order id: <%= o.id %></li>
          <li class="list-group-item list-group-item-action list-group-item-primary">Total
            price: <%= o.total_price %></li>
          <li class="list-group-item list-group-item-action list-group-item-primary">Status: <%= o.finalized ? "Processed" : "Pending" %></li>
          <% unless o.finalized? %>
            <li class="list-group-item active"><%= button_to "Process Order", admin_order_path(o.id), method: :patch, class: "btn btn-primary" %></li>
          <% else %>
            <li class="list-group-item list-group-item-success"><h4 class="text-muted">Order processed!</h4></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>