config/routes.rb
Rails.application.routes.draw do
  # home page
  root "home_page#index"

  # sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # carts
  get '/cart', to: 'carts#show'

  # cart items
  post '/cart_items', to: 'cart_items#create'

  # users
  get '/signup', to: 'users#new'

  # orders
  get '/orders', to: 'orders#index'
  post 'orders/new', to: 'orders#create'

  # order items
  post '/order_items', to: 'order_items#create'

  # resources
  resources :users, only: %i[show new create edit update]
  resources :home_page
  resources :dishes
  resources :cart_items
  resources :orders, only: %i[show new create]
  resources :order_items

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :orders, only: %i[edit index update]
    get '/', to: 'base#index'
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :dish

  validates :cart_id, presence: true
  validates :dish_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    if logged_in?
      @cart_items = current_user.cart.cart_items
    end
  end

  def new
    @cart_item = CartItem.new
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    CartItem.destroy(cart_item.id)
    redirect_to '/cart_items'
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.cart_id = current_user.cart.id
    if @cart_item.save
      flash[:success] = "Item added to your cart!"
      redirect_to root_path
    else
      flash[:danger] = 'Could not add item to the basket!'
      redirect_to root_path
    end
  end

  private

    def cart_item_params
      params.require(:cart_item).permit(:dish_id, :quantity)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_content.html.erb
<% if @cart_items.empty? %>
  <div class="empty-cart-container">
    <%= image_tag "empty-cart.png", class: "empty-cart-image", alt: "Empty cart" %>
  </div>
  <h1 class="centered-title">Seems like your cart is empty!</h1>
<% else %>
  <div id="cart-container" class="container">
    <% @cart_items.each do |ci| %>
      <div class="row cart-row">
        <div class="col cart-row-content">
          <%= image_tag ci.dish.image, class: "dish small-dish", alt: "dish" %>
        </div>
        <div class="col">
          <p class="dish-name centered-title "><%= ci.dish.title %></p>
        </div>
        <div class="col cart-row-content">
          <p class="dish-category">Category: <%= ci.dish.category %></p>
          <p class="dish-price">Price: $<%= ci.dish.price * ci.quantity %></p>
          <p class="centered-title bg-info">Quantity: <%= ci.quantity %></p>
        </div>

        <div class="col">
          <%= link_to "Remove Item", "/cart_items/#{ ci.id }", method: :delete %>
        </div>
      </div>
    <% end %>
    <div class="total-price total-price-box">Total price: $
      <% total_price = 0
         @cart_items.each do |ci|
           total_price += ci.dish.price * ci.quantity
      %>
      <% end %>
      <%= total_price %>
      <%= button_to "Place order", new_order_path(total_price: total_price) %>
    </div>
  </div>
<% end %>

app/views/cart_items/index.html.erb
<% if logged_in? %>
  <%= render "cart_items/cart_content" %>
<% else %>
  <h1 class="centered-title">Sorry, you must log in to access your cart!</h1>
<% end %>