config/routes.rb
Rails.application.routes.draw do
  # home page
  root "home_page#index"

  # sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # carts
  get '/cart', to: 'carts#show'

  # cart items
  post '/cart_items', to: 'cart_items#create'

  # users
  get '/signup', to: 'users#new'

  # orders
  get '/orders', to: 'orders#index'
  post 'orders/new', to: 'orders#create'

  # order items
  post '/order_items', to: 'order_items#create'

  # resources
  resources :users, only: %i[show new create edit update]
  resources :home_page
  resources :dishes
  resources :cart_items
  resources :orders, only: %i[show new create]
  resources :order_items

  namespace :admin do
    resources :users, only: %i[index destroy]
    resources :orders, only: %i[edit index update]
    get '/', to: 'base#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :dish

  validates :cart_id, presence: true
  validates :dish_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_one_attached :image
  has_many :cart_items

  validates :title, presence: true, length: { maximum: 20 }
  validates :category, presence: true, length: { maximum: 30 }
  validates :price, presence: true
  validates :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :dish

  validates :order_id, presence: true
  validates :dish_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_one :cart
  has_many :orders

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { email.downcase! }
  validates :name, presence: true, length: {maximum: 50}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_secure_password

  # this is used for static methods
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns the hash digest of the given string
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience
  def session_token
    remember_digest || remember
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @dish = Dish.new
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.image.attach(params[:dish][:image])
    if @dish.save
      redirect_to root_path
    else
      flash[:danger] = 'There was an error in creating a new product!'
      redirect_to root_path
    end
  end

  private

    def dish_params
      params.require(:dish).permit(:title, :category, :price, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to Eureka Caffe!"
      @cart = Cart.create(user_id: @user.id)
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "You must log in to continue!"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
  private

    def check_logged_in_as_admin
      unless logged_in? && is_admin?
        flash[:danger] = "You must be logged in as an admin to have access!"
        redirect_to login_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
require 'barby'
require 'barby/barcode'
require 'barby/barcode/qr_code'
require 'barby/outputter/png_outputter'

module OrdersHelper
  def copy_cart_items(cart_items, order_id)
    cart_items.each do |ci|
      OrderItem.create(order_id: order_id, dish_id: ci.dish_id, quantity: ci.quantity)
    end
  end

  def generate_qr(text)
    barcode = Barby::QrCode.new(text, level: :q, size: 5)
    base64_output = Base64.encode64(barcode.to_png({xdim: 5}))
    "data:image/png;base64,#{base64_output}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user && user == current_user
  end

  def is_admin?
    current_user&.is_admin?
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  # Log in as a particular user
  def log_in_as(user)
    session[:user_id] = user.id
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_footer.html.erb
<div class="admin-footer pt-lg-2">
    <div class="button-group animated fadeInDown ">
    <%= link_to "Back to Admin", admin_path, class: "btn btn-info btn-lg" %>
    <%= link_to "Users list", admin_users_path, class: "btn btn-warning btn-lg" %>
    <%= link_to "All Orders", admin_orders_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Home Page", root_path, class: "btn btn-danger btn-lg" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="page-header">
  <%= render "layouts/navbar_top" %>
  <%= render "layouts/header_content" %>
</header>

app/views/layouts/_header_content.html.erb
<div id="header-content">
  <h1 id="page-title" class="animated fadeIn">Ordering food</h1>
  <div id="rounded-line-container">
    <div class="holder animated fadeInLeft">
      <div class="smallLine smallLine1"></div>
      <div class="smallLine smallLine2"></div>
    </div>
    <%= image_tag "dining_room_52px.png", id: "dining-room-icon", alt: "Dining room icon" %>
    <div class="holder animated fadeInRight">
      <div class="smallLine smallLine1"></div>
      <div class="smallLine smallLine2"></div>
    </div>
  </div>
  <h2 id="latin-text">Maecenas vells at magna sagittis venenatis. Integer pretium auctor<br> magna, egestas justo
    gravida vitae. In lacinia auctor auctor</h2>
</div>

app/views/layouts/_navbar_top.html.erb
<div id="navbar-top" class="animated fadeInDown delay-3s">
  <div id="logo-container">
    <%= image_tag "8b1591a7-6990-4acb-8f5a-34f0af512a53.jpg", id: "logo", alt: "logo" %>
    <p>EUREKA<br>CAFFE</p>
  </div>
  <ul>
    <li><%= link_to "HOME", root_path, class: "a-home" %></li>
    <li> <%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>
    <li><a id="a-about" href="#">ABOUT</a></li>
    <li><%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>
    <% if is_admin? %>
      <li><%= link_to "ADMIN PAGE", admin_path, alt: "admin" %></li>
      <li><%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>
    <% end %>
    <% if logged_in? %>
      <li><%= link_to "CART", cart_items_path %></li>
      <li><%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>

      <li><%= link_to "MY ORDERS", orders_path %></li>
      <li><%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>

      <li><%= link_to "EDIT PROFILE", edit_user_path(current_user) %></li>
      <li><%= image_tag "orange_bullet_16.png", alt: "bullet", class: "bullet" %></li>

      <li><%= link_to "LOG OUT", logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "LOG IN / SIGN UP", login_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="admin-page-body">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <footer>
      <%= render 'layouts/admin_footer' %>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoffeeShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>